-- ============================================================
-- Hospital Management System - Database Schema & Analysis
-- RDBMS: MySQL 8.0+
-- ============================================================

CREATE DATABASE IF NOT EXISTS hospital_db;
USE hospital_db;

-- Clear existing tables if re-running script
DROP TABLE IF EXISTS billing;
DROP TABLE IF EXISTS appointments;
DROP TABLE IF EXISTS doctors;
DROP TABLE IF EXISTS patients;

-- ------------------------------------------------------------
-- 1. SCHEMA DESIGN (DDL)
-- ------------------------------------------------------------

-- Table: Patients
CREATE TABLE patients (
    patient_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    gender ENUM('Male', 'Female', 'Other') NOT NULL,
    date_of_birth DATE NOT NULL,
    contact_number VARCHAR(15) UNIQUE NOT NULL,
    address TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: Doctors
CREATE TABLE doctors (
    doctor_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    specialization VARCHAR(100) NOT NULL,
    contact_number VARCHAR(15) UNIQUE NOT NULL,
    consultation_fee DECIMAL(10,2) NOT NULL,
    status ENUM('Active', 'On Leave', 'Inactive') DEFAULT 'Active'
);

-- Table: Appointments
CREATE TABLE appointments (
    appointment_id INT AUTO_INCREMENT PRIMARY KEY,
    patient_id INT NOT NULL,
    doctor_id INT NOT NULL,
    appointment_date DATETIME NOT NULL,
    reason_for_visit TEXT,
    status ENUM('Scheduled', 'Completed', 'Cancelled') DEFAULT 'Scheduled',
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id) ON DELETE CASCADE
);

-- Table: Billing
CREATE TABLE billing (
    bill_id INT AUTO_INCREMENT PRIMARY KEY,
    appointment_id INT UNIQUE NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    payment_status ENUM('Pending', 'Paid', 'Refunded') DEFAULT 'Pending',
    payment_date DATETIME DEFAULT NULL,
    FOREIGN KEY (appointment_id) REFERENCES appointments(appointment_id) ON DELETE CASCADE
);

-- Indexes for performance optimization
CREATE INDEX idx_patient_dob ON patients(date_of_birth);
CREATE INDEX idx_appointment_date ON appointments(appointment_date);

-- ------------------------------------------------------------
-- 2. SAMPLE DATA INSERTION (DML)
-- ------------------------------------------------------------

INSERT INTO doctors (first_name, last_name, specialization, contact_number, consultation_fee) VALUES
('Aarav', 'Sharma', 'Cardiology', '9876543210', 120.00),
('Ananya', 'Patel', 'Pediatrics', '9876543211', 90.00),
('Rohan', 'Verma', 'Orthopedics', '9876543212', 150.00),
('Priya', 'Nair', 'Neurology', '9876543213', 180.00);

INSERT INTO patients (first_name, last_name, gender, date_of_birth, contact_number, address) VALUES
('Vikram', 'Singh', 'Male', '1988-05-14', '9123456780', '123 Park Street, Delhi'),
('Neha', 'Gupta', 'Female', '1995-11-23', '9123456781', '45 MG Road, Bangalore'),
('Rajesh', 'Kumar', 'Male', '1972-02-09', '9123456782', '78 Sector 15, Chandigarh'),
('Sunita', 'Rao', 'Female', '2001-08-30', '9123456783', '12 Anna Salai, Chennai');

INSERT INTO appointments (patient_id, doctor_id, appointment_date, reason_for_visit, status) VALUES
(1, 1, '2026-10-01 10:00:00', 'Chest pain checkup', 'Completed'),
(2, 2, '2026-10-02 11:30:00', 'Child wellness visit', 'Completed'),
(3, 3, '2026-10-05 14:00:00', 'Knee joint consultation', 'Completed'),
(4, 4, '2026-10-10 09:30:00', 'Migraine consultation', 'Scheduled'),
(1, 1, '2026-10-12 10:00:00', 'Cardiology follow-up', 'Scheduled');

INSERT INTO billing (appointment_id, amount, payment_status, payment_date) VALUES
(1, 120.00, 'Paid', '2026-10-01 10:45:00'),
(2, 90.00, 'Paid', '2026-10-02 12:00:00'),
(3, 150.00, 'Pending', NULL),
(4, 180.00, 'Pending', NULL);

-- ------------------------------------------------------------
-- 3. ANALYTICAL QUERIES & VIEWS (For Demonstration)
-- ------------------------------------------------------------

-- Query 1: Total revenue generated by payment status
SELECT 
    payment_status,
    COUNT(bill_id) AS total_bills,
    SUM(amount) AS total_amount
FROM billing
GROUP BY payment_status;

-- Query 2: Detailed patient appointment report using JOINs
SELECT 
    a.appointment_id,
    CONCAT(p.first_name, ' ', p.last_name) AS patient_name,
    CONCAT('Dr. ', d.first_name, ' ', d.last_name) AS doctor_name,
    d.specialization,
    a.appointment_date,
    a.status AS appointment_status,
    COALESCE(b.payment_status, 'Unbilled') AS payment_status
FROM appointments a
JOIN patients p ON a.patient_id = p.patient_id
JOIN doctors d ON a.doctor_id = d.doctor_id
LEFT JOIN billing b ON a.appointment_id = b.appointment_id
ORDER BY a.appointment_date DESC;

-- Query 3: View for quick summary of active doctor workloads
CREATE OR REPLACE VIEW view_doctor_workload AS
SELECT 
    d.doctor_id,
    CONCAT('Dr. ', d.first_name, ' ', d.last_name) AS doctor_name,
    d.specialization,
    COUNT(a.appointment_id) AS total_appointments
FROM doctors d
LEFT JOIN appointments a ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_id, doctor_name, d.specialization;

-- Query to test the view
SELECT * FROM view_doctor_workload;